# Generated by Django 5.2.7 on 2026-07-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_user',
            new_name='create_model',
        ),
        migrations.RenameModel(
            old_name='login_view',
            new_name='login_model',
        ),
    ]
