# Generated by Django 5.2.7 on 2026-07-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_create_user_create_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
