# Generated by Django 5.2.7 on 2026-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_login_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_model',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
