# Generated by Django 5.2.7 on 2026-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_student_remove_create_model_repassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('villege', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=10)),
            ],
        ),
    ]
