# Generated by Django 5.2.7 on 2026-07-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=10)),
                ('book_no', models.IntegerField()),
                ('bookName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
