# Generated by Django 5.2.7 on 2026-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('addmission_no', models.IntegerField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
